### ISSUE TITLE
501 Not Implemented

### ISSUE THREAD

**Issue by theovaldi** [stevenmaguire/trello-php#17]
Dear All

I try proxy feature, but i get error like this

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `GET http://trello.com/1/members/my/boards?key=165943b3a5836d30e676056b00047666&token=8fa7c3a9ac00a804527adcfaecc47b26c30fad67e045a28a5cd1d677a3c7bdee` resulted in a `501 Not Implemented` response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> <html><head> <meta http-equiv (truncated...) ' in C:\xampp\htdocs\trello_new\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:107 Stack trace: #0 C:\xampp\htdocs\trello_new\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\trello_new\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\trello_new\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\R in C:\xampp\htdocs\trello_new\vendor\stevenmaguire\trello-php\src\Http.php on line 273

is something wrong with my code ?

$client = new \Stevenmaguire\Services\Trello\Client(array(
    'domain' => 'http://trello.com',
    'key' => 'key',
    'secret' => 'secret',
    'name' => 'My sweet trello enabled app',
    'callbackUrl' => $currentUrl,
    'expiration' => 'never',
    'scope' => 'read',
    'token' => 'token',
    'proxy' => 'tcp://173.230.147.176:3128'

**Comment by stevenmaguire** [comment]
I find it difficult to believe your proxy is functioning correctly using the address `tcp://173.230.147.176:3128` considering the example, which was pulled from Guzzle's website, is `tcp://localhost:8125`. 

I am going to recommend you do some research into HTTP protocol, contact your network administrator, and continue to experiment with the package without raising new issues for every problem you run into. Yet again, the issues you are reporting do not indicate an issue with the code in this package and are likely caused by misconfiguration of the package on your end or undocumented network configuration that you forced to work through.
