### ISSUE TITLE
Turn SSL Verification off on curl client

### ISSUE THREAD

**Issue by molerat619** [stevenmaguire/trello-php#33]
Thanks for your great work @stevenmaguire !

Can I pass an option to turn verification of the ssl certificate off? Pretty much like so: https://stackoverflow.com/questions/39330197/laravel-local-hosted-curl-error-60-ssl-certificate

In our environment it is not possible to have an ssl certificate installed in the near future but we need the tool now so we want to turn it off temporarily.

**Comment by stevenmaguire** [comment]
@molerat619 thanks for the note. There is an undocumented (because it's a bit more "advanced") feature of this package that might help you out a bit.

You can configure and set your own HTTP client, provided it is an instance of `GuzzleHttp\ClientInterface`.

https://github.com/stevenmaguire/trello-php/blob/237a871393de66b071641137a86aa618becb70c2/src/Client.php#L72-L77

Hopefully, that helps!

**Comment by molerat619** [comment]
@stevenmaguire Thank you, that worked fine 👍
