### ISSUE TITLE
getCurrentUserBoards() not working

### ISSUE THREAD

**Issue by markodobric** [stevenmaguire/trello-php#5]
Hi Steven,

I am trying to connect with Trello but I have some problem.

I'm using your example to get access token and I get it. But when I creating client and try to call my boards I get:
   "Fatal error: Call to a member function getReasonPhrase() on a non-object in ***vendor\stevenmaguire\trello-php\src\Http.php on line 252" 

// this line work fine
$credentials = $client->getAccessToken($_GET['oauth_token'], $_GET['oauth_verifier']); 

// creating client also work
$client = new Stevenmaguire\Services\Trello\Client(array(
         'key' => ********,
         'token' => $credentials->getIdentifier()
 ));

// this line NOT WORKING!
$boards = $client->getCurrentUserBoards();

Please, can you help me. Thanks.

**Comment by stevenmaguire** [comment]
Yowza! I will look into this a bit and see if I can help.

**Comment by stevenmaguire** [comment]
The error you are receiving is due to the underlying `RequestException` having no `Response` object attached to it. I've updated the code and tests to account for this scenario. After it builds successfully and I cut a new tag, pull down the latest and try again with the following suggestion. 

It is likely that the request is failing because of a problem with your access token or key, this is not an issue with this package. This means that you may still have an exception thrown. You should wrap your code in a try/catch that expects the exception in this package to be thrown. Once this exception is thrown it should have more valuable information about what went wrong. The issue that I've corrected with this latest code change is to ensure that underlying exception has the _best available_ information.

``` php
try {
    $boards = $client->getCurrentUserBoards();
} catch (Stevenmaguire\Services\Trello\Exceptions\Exception $e) {
    $code = $e->getCode(); // Http status code from response
    $reason = $e->getMessage(); // Http status reason phrase
    $error = $e->getPrevious(); // GuzzleHttp\Exception\RequestException from http client
    $body = $e->getResponseBody(); // stdClass response body from http client
}
```

I will add another comment once the new tag is available.

**Comment by stevenmaguire** [comment]
[Tag 0.3.6](https://github.com/stevenmaguire/trello-php/releases/tag/0.3.6) is now available. Please update your project and provide some feedback about changes in behavior.

**Comment by markodobric** [comment]
Ok. Thanks a lot.

**Comment by markodobric** [comment]
Now I get following when I print `$reason = $e->getMessage()`

"cURL error 60: SSL certificate problem: self signed certificate in certificate chain."

**Comment by markodobric** [comment]
I managed to solve this problem. :)

It was a problem of XAMPP.
I just had to add `curl.cainfo = "PATH_TO/cacert.pem"` at the end of the php.ini file of XAMMP.

This solution: http://stackoverflow.com/a/16495053

**Comment by stevenmaguire** [comment]
Perfect! And yes, that problem has shown up in the past and it is commonly related to your environment configuration rather than the code in this package, as you've discovered. I am glad you resolved it and helped make the package better!
